In [330]:
import pandas as pd
import numpy as np

In [331]:
df = pd.read_csv('Uncleaned_DS_jobs.csv', low_memory=False)
df.index = df.index + 1
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 1000)
df.drop('index',axis = 1, inplace = True)
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
1,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
2,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
3,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
4,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
5,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [332]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 672 entries, 1 to 672
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          672 non-null    object
 1   Salary Estimate    672 non-null    object
 2   Job Description    672 non-null    object
 3   Rating             672 non-null    float64
 4   Company Name       672 non-null    object
 5   Location           672 non-null    object
 6   Headquarters       672 non-null    object
 7   Size               672 non-null    object
 8   Founded            672 non-null    int64
 9   Type of ownership  672 non-null    object
 10  Industry           672 non-null    object
 11  Sector             672 non-null    object
 12  Revenue            672 non-null    object
 13  Competitors        672 non-null    object
dtypes: float64(1), int64(1), object(12)
memory usage: 73.6+ KB

In [333]:
#check null
df.isnull().sum()

Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         0
Location             0
Headquarters         0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
Competitors          0
dtype: int64

### Remove duplicated

In [334]:
#check duplicated
print(df[df.duplicated()].shape)

(13, 14)

In [335]:
#Data duplicated
df[df.duplicated()]

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
136,Machine Learning Engineer,$90K-$109K (Glassdoor est.),Role Description\nTriplebyte screens and evalu...,3.2,Triplebyte\n3.2,Remote,"San Francisco, CA",51 to 200 employees,2015,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1
137,Senior Data Engineer,$90K-$109K (Glassdoor est.),Lendio is looking to fill a position for a Sen...,4.9,Lendio\n4.9,"Lehi, UT","Lehi, UT",201 to 500 employees,2011,Company - Private,Lending,Finance,$50 to $100 million (USD),-1
359,Data Scientist,$122K-$146K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
360,Data Scientist,$122K-$146K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
361,Data Scientist,$122K-$146K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
362,Data Scientist,$122K-$146K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
363,Data Scientist,$122K-$146K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
390,Data Scientist,$110K-$163K (Glassdoor est.),"Job Description\nAs a Data Scientist, you will...",-1.0,HireAi,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
497,Data Scientist,$95K-$119K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
498,Data Scientist,$95K-$119K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
499,Data Scientist,$95K-$119K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
500,Data Scientist,$95K-$119K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
501,Data Scientist,$95K-$119K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1

In [336]:
#Drop duplicated
df.drop_duplicates(inplace = True)
df.reset_index(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 659 entries, 0 to 658
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              659 non-null    int64
 1   Job Title          659 non-null    object
 2   Salary Estimate    659 non-null    object
 3   Job Description    659 non-null    object
 4   Rating             659 non-null    float64
 5   Company Name       659 non-null    object
 6   Location           659 non-null    object
 7   Headquarters       659 non-null    object
 8   Size               659 non-null    object
 9   Founded            659 non-null    int64
 10  Type of ownership  659 non-null    object
 11  Industry           659 non-null    object
 12  Sector             659 non-null    object
 13  Revenue            659 non-null    object
 14  Competitors        659 non-null    object
dtypes: float64(1), int64(2), object(12)
memory usage: 77.4+ KB

### Remove numbers from Company Name column

In [337]:
df['Company Name']

0                                       Healthfirst\n3.1
1                                           ManTech\n4.2
2                                    Analysis Group\n3.8
3                                           INFICON\n3.5
4                                Affinity Solutions\n2.9
5                                       HG Insights\n4.2
6                                          Novartis\n3.9
7                                            iRobot\n3.5
8                                     Intuit - Data\n4.4
9                                XSELL Technologies\n3.6
10                                          Novetta\n4.5
11                                         1904labs\n4.7
12                                             PNNL\n3.7
13                             Old World Industries\n3.1
14                      Mathematica Policy Research\n3.4
15             Guzman & Griffin Technologies (GGTI)\n4.4
16                           Upside Business Travel\n4.1
17                                          Buckman\n3.5
18                        Insight Enterprises, Inc.\n4.2
19                                     Tower Health\n3.5
20                                       Triplebyte\n3.2
21                                       PulsePoint\n4.3
22                                         Exponent\n3.5
23                                    Guardian Life\n3.5
24           Spectrum Communications and Consulting\n3.4
25                                Oversight Systems\n4.7
26                                              LSQ\n4.2
27                           MIT Lincoln Laboratory\n3.8
28                               Kingfisher Systems\n4.5
29                                        Formation\n2.8
30                                   Analysis Group\n3.8
31                                         Novartis\n3.9
32                                    Cohere Health\n5.0
33                                 Acuity Insurance\n4.8
34                                             Chef\n3.6
35                               Puget Sound Energy\n3.3
36                                 Sandhills Global\n2.7
37                                  A Place for Mom\n2.7
38                        Great-Circle Technologies\n2.2
39                                      Edmunds.com\n3.4
40                        Cambridge Associates, LLC\n3.1
41                         Liberty Mutual Insurance\n3.4
42                                           Cenlar\n2.6
43                              Arsenal Biosciences\n5.0
44                                        Eversight\n4.2
45                                           Pfizer\n4.1
46                                          Klaviyo\n4.8
47                            Intellectual Ventures\n3.3
48                                          GovTech\n3.7
49                                       Quick Base\n4.3
50                                 Giving Assistant\n4.8
51                                           Takeda\n3.7
52                                         Netskope\n4.0
53                                      IT Concepts\n4.8
54                                           iSeatz\n3.5
55                              Summa Health System\n3.7
56                                      Benson Hill\n3.5
57                                          Twitter\n4.1
58                         Postmates - Corporate HQ\n3.2
59                                     Envision LLC\n4.5
60                                         Swiss Re\n3.8
61                    Systems & Technology Research\n4.5
62                                           iRobot\n3.5
63                                      HG Insights\n4.2
64                                      Dermalogica\n3.8
65                         Bayview Asset Management\n3.7
66                               Via Transportation\n3.7
67                                    Grid Dynamics\n4.0
68                                      Tempus Labs\n3.3
69                                           CareDx\n2.5
70                                             IZEA\n4.2
71                                      Tempus Labs\n3.3
72                                         Autodesk\n4.0
73                                      Caterpillar\n3.7
74                              New England Biolabs\n4.9
75                                 Allied Solutions\n3.4
76                                      Healthfirst\n3.1
77                               The Knot Worldwide\n3.5
78                                    IFG Companies\n2.9
79                                           Amyris\n3.3
80                                      AstraZeneca\n4.0
81                                         Powertek\n3.6
82                                  Object Partners\n4.7
83                                  The Mom Project\n4.9
84                               Lightspeed Systems\n4.3
85                                           Stripe\n4.0
86                         Comprehensive Healthcare\n2.6
87                     Fullpower Technologies, Inc.\n4.5
88                                          Klaviyo\n4.8
89                                             Mars\n3.9
90                                      AstraZeneca\n4.0
91                                 NuWave Solutions\n4.4
92                                          ManTech\n4.2
93                                     Merrick Bank\n3.6
94                      Mathematica Policy Research\n3.4
95                                    Intuit - Data\n4.4
96                                           QOMPLX\n3.5
97                                             Mars\n3.9
98                                         GutCheck\n3.8
99                  Inter-American Development Bank\n3.5
100                                          Avlino\n4.9
101                                 Stratagem Group\n4.4
102                                       Evidation\n4.1
103                                        Autodesk\n4.0
104                                   Intuit - Data\n4.4
105                               Tecolote Research\n3.8
106                                   Tivity Health\n3.2
107                                             hc1\n2.9
108                                         HP Inc.\n4.1
109                                            SAIC\n3.7
110                               AllianceBernstein\n3.2
111                                  Big Huge Games\n4.9
112                              Maxar Technologies\n3.5
113                                      Phantom AI\n5.0
114                                          Noblis\n4.0
115                                   Spring Health\n3.6
116                                       ClearEdge\n4.0
117                               AllianceBernstein\n3.2
118                             Arsenal Biosciences\n5.0
119                                  GetWellNetwork\n4.8
120                                  TACG Solutions\n4.5
121                                           Scoop\n4.7
122                                         Novetta\n4.5
123                                            IZEA\n4.2
124                                     Montway Inc\n3.4
125                                Juniper Networks\n3.8
126                                        1904labs\n4.7
127                              XSELL Technologies\n3.6
128                                            IZEA\n4.2
129                                Juniper Networks\n3.8
130                                     Notion Labs\n5.0
131                                          Lendio\n4.9
132                                   Direct Agents\n4.4
133                                    NAVEX Global\n3.3
134                                      Triplebyte\n3.2
135                                         Upstart\n4.2
136                                    Envision LLC\n4.5
137                                        AppLovin\n4.8
138                                 ISO New England\n3.8
139                                      Relativity\n3.7
140                                Tempo Automation\n3.3
141                                           MITRE\n3.3
142                     Expedition Technology, Inc.\n5.0
143                                         Evidera\n3.8
144                         Plymouth Rock Assurance\n3.4
145                                Crown Bioscience\n2.4
146                                  GNS Healthcare\n2.9
147                                      OneMagnify\n4.4
148                                        SPECTRUM\n2.9
149                Advanced BioScience Laboratories\n2.7
150                            Procore Technologies\n4.2
151                                        Ritedose\n3.5
152                             Covid-19 Search Partners
153                                      bioMérieux\n4.2
154                                         Novetta\n4.5
155            Guzman & Griffin Technologies (GGTI)\n4.4
156                                  Radical Convergence
157                                          Leidos\n3.5
158                                      Demandbase\n4.5
159                               Shelter Insurance\n4.1
160                              Maxar Technologies\n3.5
161                                            USAC\n2.7
162         General Dynamics Information Technology\n3.4
163                                        Offerpad\n4.4
164                                        Autodesk\n4.0
165                                        Autodesk\n4.0
166                        Magna International Inc.\n3.5
167                                United BioSource\n2.3
168                                           Kelly\n3.4
169                                     Tempus Labs\n3.3
170                                           C3.ai\n4.7
171                                  Quartet Health\n3.9
172                       Midland Credit Management\n3.3
173                                     Tempus Labs\n3.3
174                      Resurgent Capital Services\n4.4
175                                            PNNL\n3.7
176                                         Buckman\n3.5
177                                         Buckman\n3.5
178                                         Evidera\n3.8
179                                       webfx.com\n4.7
180                                   Argo Group US\n3.5
181                                BWX Technologies\n3.3
182                                         Life360\n3.9
183                                      MassMutual\n3.7
184                                          Natera\n3.9
185                                       Genentech\n4.0
186                                         Ntrepid\n4.2
187                                Constant Contact\n3.6
188                                    Sage Intacct\n4.7
189                                  Shape Security\n4.1
190                                     AstraZeneca\n4.0
191                                      SkillSoniq\n5.0
192                                     AstraZeneca\n4.0
193                                   Joby Aviation\n4.3
194              Cook Children's Health Care System\n3.8
195                             Rubius Therapeutics\n3.8
196                 GreatAmerica Financial Services\n4.6
197                          Upside Business Travel\n4.1
198          Spectrum Communications and Consulting\n3.4
199                                        Coverent\n4.1
200                                            Mteq\n3.7
201                                   Rocket Lawyer\n4.4
202                                        Novartis\n3.9
203                      Alion Science & Technology\n3.6
204                                         Novetta\n4.5
205                                       Protolabs\n3.7
206                                 Quest Integrity\n2.9
207                        Phoenix Operations Group\n5.0
208                                        Dice.com\n3.4
209                              Maxar Technologies\n3.5
210                        Phoenix Operations Group\n5.0
211                                         Klaviyo\n4.8
212                    Southwest Research Institute\n3.9
213                                     AstraZeneca\n4.0
214                               The Buffalo Group\n4.3
215          Central California Alliance for Health\n3.5
216                                      MassMutual\n3.7
217                                     Tempus Labs\n3.3
218     Security Finance Corporation of Spartanburg\n3.1
219                                      PulsePoint\n4.3
220                                             LSQ\n4.2
221                      Resurgent Capital Services\n4.4
222                                        Opendoor\n3.6
223                      Global Data Management Inc\n4.5
224                                 Photon Infotech\n3.0
225                                             REE\n5.0
226                    Riverside Research Institute\n3.6
227                                   T. Rowe Price\n3.6
228                                         Encode, Inc.
229                                         Evidera\n3.8
230                                BWX Technologies\n3.3
231                           Brighthouse Financial\n3.8
232                                   Argo Group US\n3.5
233                              II-VI Incorporated\n3.3
234                                   Surya Systems\n4.6
235                                          PayPal\n3.8
236                                         Life360\n3.9
237                         Predictive Research Inc\n3.9
238                               Oversight Systems\n4.7
239                                Acuity Insurance\n4.8
240                                        1010data\n3.1
241                                           Gigya\n3.6
242                                Genesis Research\n5.0
243                                          Sanofi\n3.7
244                                   XPO Logistics\n3.7
245                                      Trace Data\n3.9
246                                        Descript\n4.3
247                     Rincon Research Corporation\n4.2
248                                      MassMutual\n3.7
249                                     Better Hire\n4.0
250                                 Parker Hannifin\n3.3
251                                          Gallup\n4.1
252                                     Insider Inc\n3.3
253                           Rapid Value Solutions\n3.9
254                                        Battelle\n3.1
255                                         Ntrepid\n4.2
256                           The Drive Media, Inc.\n5.0
257                              Affinity Solutions\n2.9
258                                    Sage Intacct\n4.7
259                                Constant Contact\n3.6
260                          MIT Lincoln Laboratory\n3.8
261                              Puget Sound Energy\n3.3
262           Pacific Northwest National Laboratory\n3.7
263                                  Analysis Group\n3.8
264                                 US Pharmacopeia\n3.2
265                                   Itlize Global\n4.6
266                                            eBay\n3.5
267                                           Paige\n5.0
268                                  Shape Security\n4.1
269                                         ABIOMED\n4.1
270                                         Comcast\n3.5
271                                  Metronome, LLC\n3.2
272                                      SkillSoniq\n5.0
273                 Lawrence Livermore National Lab\n4.7
274                              FHLBank Pittsburgh\n3.8
275                                          Jacobs\n3.6
276                                         Klaviyo\n4.8
277                       Underwriters Laboratories\n3.3
278                                     Altus Group\n3.7
279                                           Jobot\n5.0
280                                       Trovetechs Inc
281                                     Edmunds.com\n3.4
282                                   Cohere Health\n5.0
283                                       Trovetechs Inc
284                                     AstraZeneca\n4.0
285                             Oshkosh Corporation\n4.2
286                                   Joby Aviation\n4.3
287                                          Mackin\n3.4
288                                             PETADATA
289                             VBeyond Corporation\n4.4
290                                          Leidos\n3.5
291                                        Take-Two\n3.7
292                                   Colony Brands\n3.7
293                                     Capio Group\n4.1
294                                        SleePare\n3.4
295                                      ShorePoint\n4.5
296                                         Dolphin\n3.5
297                                 TE Connectivity\n3.6
298                               State of Virginia\n3.2
299                                      TA Digital\n3.7
300                              Market America Inc\n4.0
301                                      Triplebyte\n3.2
302                              Kingfisher Systems\n4.5
303                                      TrueAccord\n3.4
304                                ALTA IT Services\n3.9
305                                  Kollasoft Inc.\n3.2
306                                  Kollasoft Inc.\n3.2
307                    ASRC Federal Holding Company\n3.4
308                                Adwait Algorithm\n4.4
309              Cook Children's Health Care System\n3.8
310                             Rubius Therapeutics\n3.8
311                                    Cambridge FX\n3.5
312                                       Metromile\n3.8
313                                          Criteo\n3.9
314                       Advance Sourcing Concepts\n3.4
315                        Enterprise Solutions Inc\n3.8
316                 GreatAmerica Financial Services\n4.6
317                                         Microagility
318                         Conch Technologies, Inc\n4.6
319                                             GSK\n3.9
320                             Rainmaker Resources, LLC
321                                         GovTech\n3.7
322                           Intellectual Ventures\n3.3
323                                   Rocket Lawyer\n4.4
324                       22nd Century Technologies\n3.7
325                                          Huxley\n3.3
326                                      FM Systems\n3.4
327                                               B4Corp
328                                            Mteq\n3.7
329    Blue Cross and Blue Shield of North Carolina\n3.7
330                                     Jane Street\n4.8
331                                           SSATI\n5.0
332                                        Novartis\n3.9
333                    Solving IT International Inc\n3.4
334                   The Davey Tree Expert Company\n3.3
335                                        Centauri\n4.6
336                                        Stride Search
337                  Software Engineering Institute\n2.6
338                                     Dermalogica\n3.8
339                                    TechProjects\n4.8
340                                      7Park Data\n3.9
341                                        Netskope\n4.0
342                                       Eversight\n4.2
343                                       Protolabs\n3.7
344                    Ameritas Life Insurance Corp\n3.0
345                                 Western Digital\n3.5
346                                  Shimento, Inc.\n2.9
347                                         Averity\n5.0
348                              Praxis Engineering\n4.7
349                                     Point72 Ventures

In [338]:
#remove number after '\n' (=get name of company before \n)
df1 = df['Company Name'].str.split('\n').str[0]
df.update(df1)
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,1,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,2,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,3,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,4,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,5,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

### Create State Column from Location column

In [339]:
#extract State from Location
df['State'] = df['Location'].str.split(',').str[-1].str.strip(' ')
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,State
0,1,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",NY
1,2,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,VA
2,3,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,MA
3,4,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",MA
4,5,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",NY

In [340]:
df['State'].value_counts().to_frame()

               State
CA               154
VA                89
MA                62
NY                52
MD                40
IL                30
DC                26
TX                17
WA                16
OH                14
PA                12
MO                12
United States     11
NJ                10
CO                10
NC                 9
GA                 9
TN                 8
FL                 8
OK                 6
WI                 6
Remote             5
IN                 5
MI                 5
CT                 4
AL                 4
MN                 4
AZ                 4
NE                 3
IA                 3
RI                 2
New Jersey         2
SC                 2
OR                 2
UT                 2
Utah               2
NH                 2
MS                 1
LA                 1
KS                 1
Texas              1
DE                 1
California         1
WV                 1

In [341]:
def rename_state(rs):
    if rs == 'United States':
        return 'U.S'
    elif rs == 'New Jersey':
        return 'NJ'
    elif rs == 'Texas':
        return 'TX'
    elif rs == 'California':
        return 'CA'
    elif rs =='Utah':
        return 'UT'
    else:
        return rs

df['State'] = df['State'].apply(rename_state)

In [342]:
df['State'].value_counts().to_frame()

        State
CA        155
VA         89
MA         62
NY         52
MD         40
IL         30
DC         26
TX         18
WA         16
OH         14
PA         12
NJ         12
MO         12
U.S        11
CO         10
GA          9
NC          9
FL          8
TN          8
OK          6
WI          6
MI          5
Remote      5
IN          5
AZ          4
CT          4
MN          4
AL          4
UT          4
IA          3
NE          3
SC          2
OR          2
RI          2
NH          2
MS          1
LA          1
KS          1
DE          1
WV          1

### Cleaning Salary Estimate column

In [343]:
df['Salary Estimate']

0      $137K-$171K (Glassdoor est.)
1      $137K-$171K (Glassdoor est.)
2      $137K-$171K (Glassdoor est.)
3      $137K-$171K (Glassdoor est.)
4      $137K-$171K (Glassdoor est.)
5      $137K-$171K (Glassdoor est.)
6      $137K-$171K (Glassdoor est.)
7      $137K-$171K (Glassdoor est.)
8      $137K-$171K (Glassdoor est.)
9      $137K-$171K (Glassdoor est.)
10     $137K-$171K (Glassdoor est.)
11     $137K-$171K (Glassdoor est.)
12     $137K-$171K (Glassdoor est.)
13     $137K-$171K (Glassdoor est.)
14     $137K-$171K (Glassdoor est.)
15     $137K-$171K (Glassdoor est.)
16     $137K-$171K (Glassdoor est.)
17     $137K-$171K (Glassdoor est.)
18     $137K-$171K (Glassdoor est.)
19     $137K-$171K (Glassdoor est.)
20     $137K-$171K (Glassdoor est.)
21     $137K-$171K (Glassdoor est.)
22     $137K-$171K (Glassdoor est.)
23     $137K-$171K (Glassdoor est.)
24     $137K-$171K (Glassdoor est.)
25     $137K-$171K (Glassdoor est.)
26     $137K-$171K (Glassdoor est.)
27     $137K-$171K (Glassdoor est.)
28     $137K-$171K (Glassdoor est.)
29     $137K-$171K (Glassdoor est.)
30      $75K-$131K (Glassdoor est.)
31      $75K-$131K (Glassdoor est.)
32      $75K-$131K (Glassdoor est.)
33      $75K-$131K (Glassdoor est.)
34      $75K-$131K (Glassdoor est.)
35      $75K-$131K (Glassdoor est.)
36      $75K-$131K (Glassdoor est.)
37      $75K-$131K (Glassdoor est.)
38      $75K-$131K (Glassdoor est.)
39      $75K-$131K (Glassdoor est.)
40      $75K-$131K (Glassdoor est.)
41      $75K-$131K (Glassdoor est.)
42      $75K-$131K (Glassdoor est.)
43      $75K-$131K (Glassdoor est.)
44      $75K-$131K (Glassdoor est.)
45      $75K-$131K (Glassdoor est.)
46      $75K-$131K (Glassdoor est.)
47      $75K-$131K (Glassdoor est.)
48      $75K-$131K (Glassdoor est.)
49      $75K-$131K (Glassdoor est.)
50      $75K-$131K (Glassdoor est.)
51      $75K-$131K (Glassdoor est.)
52      $75K-$131K (Glassdoor est.)
53      $75K-$131K (Glassdoor est.)
54      $75K-$131K (Glassdoor est.)
55      $75K-$131K (Glassdoor est.)
56      $75K-$131K (Glassdoor est.)
57      $75K-$131K (Glassdoor est.)
58      $75K-$131K (Glassdoor est.)
59      $75K-$131K (Glassdoor est.)
60      $75K-$131K (Glassdoor est.)
61      $75K-$131K (Glassdoor est.)
62      $79K-$131K (Glassdoor est.)
63      $79K-$131K (Glassdoor est.)
64      $79K-$131K (Glassdoor est.)
65      $79K-$131K (Glassdoor est.)
66      $79K-$131K (Glassdoor est.)
67      $79K-$131K (Glassdoor est.)
68      $79K-$131K (Glassdoor est.)
69      $79K-$131K (Glassdoor est.)
70      $79K-$131K (Glassdoor est.)
71      $79K-$131K (Glassdoor est.)
72      $79K-$131K (Glassdoor est.)
73      $79K-$131K (Glassdoor est.)
74      $79K-$131K (Glassdoor est.)
75      $79K-$131K (Glassdoor est.)
76      $79K-$131K (Glassdoor est.)
77      $79K-$131K (Glassdoor est.)
78      $79K-$131K (Glassdoor est.)
79      $79K-$131K (Glassdoor est.)
80      $79K-$131K (Glassdoor est.)
81      $79K-$131K (Glassdoor est.)
82      $79K-$131K (Glassdoor est.)
83      $79K-$131K (Glassdoor est.)
84      $79K-$131K (Glassdoor est.)
85      $79K-$131K (Glassdoor est.)
86      $79K-$131K (Glassdoor est.)
87      $79K-$131K (Glassdoor est.)
88      $79K-$131K (Glassdoor est.)
89      $79K-$131K (Glassdoor est.)
90      $79K-$131K (Glassdoor est.)
91      $79K-$131K (Glassdoor est.)
92      $79K-$131K (Glassdoor est.)
93      $79K-$131K (Glassdoor est.)
94      $99K-$132K (Glassdoor est.)
95      $99K-$132K (Glassdoor est.)
96      $99K-$132K (Glassdoor est.)
97      $99K-$132K (Glassdoor est.)
98      $99K-$132K (Glassdoor est.)
99      $99K-$132K (Glassdoor est.)
100     $99K-$132K (Glassdoor est.)
101     $99K-$132K (Glassdoor est.)
102     $99K-$132K (Glassdoor est.)
103     $99K-$132K (Glassdoor est.)
104     $99K-$132K (Glassdoor est.)
105     $99K-$132K (Glassdoor est.)
106     $99K-$132K (Glassdoor est.)
107     $99K-$132K (Glassdoor est.)
108     $99K-$132K (Glassdoor est.)
109     $99K-$132K (Glassdoor est.)
110     $99K-$132K (Glassdoor est.)
111     $99K-$132K (Glassdoor est.)
112     $99K-$132K (Glassdoor est.)
113     $99K-$132K (Glassdoor est.)
114     $99K-$132K (Glassdoor est.)
115     $99K-$132K (Glassdoor est.)
116     $99K-$132K (Glassdoor est.)
117     $99K-$132K (Glassdoor est.)
118     $99K-$132K (Glassdoor est.)
119     $99K-$132K (Glassdoor est.)
120     $99K-$132K (Glassdoor est.)
121     $99K-$132K (Glassdoor est.)
122     $99K-$132K (Glassdoor est.)
123     $99K-$132K (Glassdoor est.)
124     $99K-$132K (Glassdoor est.)
125     $99K-$132K (Glassdoor est.)
126     $90K-$109K (Glassdoor est.)
127     $90K-$109K (Glassdoor est.)
128     $90K-$109K (Glassdoor est.)
129     $90K-$109K (Glassdoor est.)
130     $90K-$109K (Glassdoor est.)
131     $90K-$109K (Glassdoor est.)
132     $90K-$109K (Glassdoor est.)
133     $90K-$109K (Glassdoor est.)
134     $90K-$109K (Glassdoor est.)
135     $90K-$109K (Glassdoor est.)
136     $90K-$109K (Glassdoor est.)
137     $90K-$109K (Glassdoor est.)
138     $90K-$109K (Glassdoor est.)
139     $90K-$109K (Glassdoor est.)
140     $90K-$109K (Glassdoor est.)
141     $90K-$109K (Glassdoor est.)
142     $90K-$109K (Glassdoor est.)
143     $90K-$109K (Glassdoor est.)
144     $90K-$109K (Glassdoor est.)
145     $90K-$109K (Glassdoor est.)
146     $90K-$109K (Glassdoor est.)
147     $90K-$109K (Glassdoor est.)
148     $90K-$109K (Glassdoor est.)
149     $90K-$109K (Glassdoor est.)
150     $90K-$109K (Glassdoor est.)
151     $90K-$109K (Glassdoor est.)
152     $90K-$109K (Glassdoor est.)
153     $90K-$109K (Glassdoor est.)
154    $101K-$165K (Glassdoor est.)
155    $101K-$165K (Glassdoor est.)
156    $101K-$165K (Glassdoor est.)
157    $101K-$165K (Glassdoor est.)
158    $101K-$165K (Glassdoor est.)
159    $101K-$165K (Glassdoor est.)
160    $101K-$165K (Glassdoor est.)
161    $101K-$165K (Glassdoor est.)
162    $101K-$165K (Glassdoor est.)
163    $101K-$165K (Glassdoor est.)
164    $101K-$165K (Glassdoor est.)
165    $101K-$165K (Glassdoor est.)
166    $101K-$165K (Glassdoor est.)
167    $101K-$165K (Glassdoor est.)
168    $101K-$165K (Glassdoor est.)
169    $101K-$165K (Glassdoor est.)
170    $101K-$165K (Glassdoor est.)
171    $101K-$165K (Glassdoor est.)
172    $101K-$165K (Glassdoor est.)
173    $101K-$165K (Glassdoor est.)
174    $101K-$165K (Glassdoor est.)
175      $56K-$97K (Glassdoor est.)
176      $56K-$97K (Glassdoor est.)
177      $56K-$97K (Glassdoor est.)
178      $56K-$97K (Glassdoor est.)
179      $56K-$97K (Glassdoor est.)
180      $56K-$97K (Glassdoor est.)
181      $56K-$97K (Glassdoor est.)
182      $56K-$97K (Glassdoor est.)
183      $56K-$97K (Glassdoor est.)
184      $56K-$97K (Glassdoor est.)
185      $56K-$97K (Glassdoor est.)
186      $56K-$97K (Glassdoor est.)
187      $56K-$97K (Glassdoor est.)
188      $56K-$97K (Glassdoor est.)
189      $56K-$97K (Glassdoor est.)
190      $56K-$97K (Glassdoor est.)
191      $56K-$97K (Glassdoor est.)
192      $56K-$97K (Glassdoor est.)
193      $56K-$97K (Glassdoor est.)
194      $56K-$97K (Glassdoor est.)
195      $56K-$97K (Glassdoor est.)
196      $56K-$97K (Glassdoor est.)
197     $79K-$106K (Glassdoor est.)
198     $79K-$106K (Glassdoor est.)
199     $79K-$106K (Glassdoor est.)
200     $79K-$106K (Glassdoor est.)
201     $79K-$106K (Glassdoor est.)
202     $79K-$106K (Glassdoor est.)
203     $79K-$106K (Glassdoor est.)
204     $79K-$106K (Glassdoor est.)
205     $79K-$106K (Glassdoor est.)
206     $79K-$106K (Glassdoor est.)
207     $79K-$106K (Glassdoor est.)
208     $79K-$106K (Glassdoor est.)
209     $79K-$106K (Glassdoor est.)
210     $79K-$106K (Glassdoor est.)
211     $79K-$106K (Glassdoor est.)
212     $79K-$106K (Glassdoor est.)
213     $79K-$106K (Glassdoor est.)
214     $79K-$106K (Glassdoor est.)
215     $79K-$106K (Glassdoor est.)
216     $79K-$106K (Glassdoor est.)
217     $79K-$106K (Glassdoor est.)
218     $79K-$106K (Glassdoor est.)
219     $71K-$123K (Glassdoor est.)
220     $71K-$123K (Glassdoor est.)
221     $71K-$123K (Glassdoor est.)
222     $71K-$123K (Glassdoor est.)
223     $71K-$123K (Glassdoor est.)
224     $71K-$123K (Glassdoor est.)
225     $71K-$123K (Glassdoor est.)
226     $71K-$123K (Glassdoor est.)
227     $71K-$123K (Glassdoor est.)
228     $71K-$123K (Glassdoor est.)
229     $71K-$123K (Glassdoor est.)
230     $71K-$123K (Glassdoor est.)
231     $71K-$123K (Glassdoor est.)
232     $71K-$123K (Glassdoor est.)
233     $71K-$123K (Glassdoor est.)
234     $71K-$123K (Glassdoor est.)
235     $71K-$123K (Glassdoor est.)
236     $71K-$123K (Glassdoor est.)
237     $71K-$123K (Glassdoor est.)
238     $90K-$124K (Glassdoor est.)
239     $90K-$124K (Glassdoor est.)
240     $90K-$124K (Glassdoor est.)
241     $90K-$124K (Glassdoor est.)
242     $90K-$124K (Glassdoor est.)
243     $90K-$124K (Glassdoor est.)
244     $90K-$124K (Glassdoor est.)
245     $90K-$124K (Glassdoor est.)
246     $90K-$124K (Glassdoor est.)
247     $90K-$124K (Glassdoor est.)
248     $90K-$124K (Glassdoor est.)
249     $90K-$124K (Glassdoor est.)
250     $90K-$124K (Glassdoor est.)
251     $90K-$124K (Glassdoor est.)
252     $90K-$124K (Glassdoor est.)
253     $90K-$124K (Glassdoor est.)
254     $90K-$124K (Glassdoor est.)
255     $90K-$124K (Glassdoor est.)
256     $90K-$124K (Glassdoor est.)
257     $90K-$124K (Glassdoor est.)
258     $90K-$124K (Glassdoor est.)
259     $90K-$124K (Glassdoor est.)
260     $91K-$150K (Glassdoor est.)
261     $91K-$150K (Glassdoor est.)
262     $91K-$150K (Glassdoor est.)
263     $91K-$150K (Glassdoor est.)
264     $91K-$150K (Glassdoor est.)
265     $91K-$150K (Glassdoor est.)
266     $91K-$150K (Glassdoor est.)
267     $91K-$150K (Glassdoor est.)
268     $91K-$150K (Glassdoor est.)
269     $91K-$150K (Glassdoor est.)
270     $91K-$150K (Glassdoor est.)
271     $91K-$150K (Glassdoor est.)
272     $91K-$150K (Glassdoor est.)
273     $91K-$150K (Glassdoor est.)
274     $91K-$150K (Glassdoor est.)
275     $91K-$150K (Glassdoor est.)
276     $91K-$150K (Glassdoor est.)
277     $91K-$150K (Glassdoor est.)
278     $91K-$150K (Glassdoor est.)
279     $91K-$150K (Glassdoor est.)
280     $91K-$150K (Glassdoor est.)
281    $141K-$225K (Glassdoor est.)
282    $141K-$225K (Glassdoor est.)
283    $141K-$225K (Glassdoor est.)
284    $141K-$225K (Glassdoor est.)
285    $141K-$225K (Glassdoor est.)
286    $141K-$225K (Glassdoor est.)
287    $141K-$225K (Glassdoor est.)
288    $141K-$225K (Glassdoor est.)
289    $141K-$225K (Glassdoor est.)
290    $141K-$225K (Glassdoor est.)
291    $141K-$225K (Glassdoor est.)
292    $141K-$225K (Glassdoor est.)
293    $141K-$225K (Glassdoor est.)
294    $141K-$225K (Glassdoor est.)
295    $141K-$225K (Glassdoor est.)
296    $141K-$225K (Glassdoor est.)
297    $141K-$225K (Glassdoor est.)
298    $141K-$225K (Glassdoor est.)
299    $141K-$225K (Glassdoor est.)
300    $141K-$225K (Glassdoor est.)
301      $145K-$225K(Employer est.)
302      $145K-$225K(Employer est.)
303      $145K-$225K(Employer est.)
304      $145K-$225K(Employer est.)
305      $145K-$225K(Employer est.)
306      $145K-$225K(Employer est.)
307      $145K-$225K(Employer est.)
308      $145K-$225K(Employer est.)
309      $145K-$225K(Employer est.)
310      $145K-$225K(Employer est.)
311      $145K-$225K(Employer est.)
312      $145K-$225K(Employer est.)
313      $145K-$225K(Employer est.)
314      $145K-$225K(Employer est.)
315      $145K-$225K(Employer est.)
316      $145K-$225K(Employer est.)
317      $145K-$225K(Employer est.)
318      $145K-$225K(Employer est.)
319      $145K-$225K(Employer est.)
320      $145K-$225K(Employer est.)
321     $79K-$147K (Glassdoor est.)
322     $79K-$147K (Glassdoor est.)
323     $79K-$147K (Glassdoor est.)
324     $79K-$147K (Glassdoor est.)
325     $79K-$147K (Glassdoor est.)
326     $79K-$147K (Glassdoor est.)
327     $79K-$147K (Glassdoor est.)
328     $79K-$147K (Glassdoor est.)
329     $79K-$147K (Glassdoor est.)
330     $79K-$147K (Glassdoor est.)
331     $79K-$147K (Glassdoor est.)
332     $79K-$147K (Glassdoor est.)
333     $79K-$147K (Glassdoor est.)
334     $79K-$147K (Glassdoor est.)
335     $79K-$147K (Glassdoor est.)
336     $79K-$147K (Glassdoor est.)
337     $79K-$147K (Glassdoor est.)
338     $79K-$147K (Glassdoor est.)
339     $79K-$147K (Glassdoor est.)
340     $79K-$147K (Glassdoor est.)
341    $122K-$146K (Glassdoor est.)
342    $122K-$146K (Glassdoor est.)
343    $122K-$146K (Glassdoor est.)
344    $122K-$146K (Glassdoor est.)
345    $122K-$146K (Glassdoor est.)
346    $122K-$146K (Glassdoor est.)
347    $122K-$146K (Glassdoor est.)
348    $122K-$146K (Glassdoor est.)
349    $122K-$146K (Glassdoor est.)
350    $122K-$146K (Glassdoor est.)
351    $122K-$146K (Glassdoor est.)
352    $122K-$146K (Glassdoor est.)
353    $122K-$146K (Glassdoor est.)
354    $122K-$146K (Glassdoor est.)
355    $122K-$146K (Glassdoor est.)
356    $122K-$146K (Glassdoor est.)
357    $112K-$116K (Glassdoor est.)
358    $112K-$116K (Glassdoor est.)
359    $112K-$116K (Glassdoor est.)
360    $112K-$116K (Glassdoor est.)
361    $112K-$116K (Glassdoor est.)
362    $112K-$116K (Glassdoor est.)
363    $112K-$116K (Glassdoor est.)
364    $112K-$116K (Glassdoor est.)
365    $112K-$116K (Glassdoor est.)
366    $112K-$116K (Glassdoor est.)
367    $112K-$116K (Glassdoor est.)
368    $112K-$116K (Glassdoor est.)
369    $112K-$116K (Glassdoor est.)
370    $112K-$116K (Glassdoor est.)
371    $112K-$116K (Glassdoor est.)
372    $112K-$116K (Glassdoor est.)
373    $112K-$116K (Glassdoor est.)
374    $112K-$116K (Glassdoor est.)
375    $112K-$116K (Glassdoor est.)
376    $112K-$116K (Glassdoor est.)
377    $112K-$116K (Glassdoor est.)
378    $110K-$163K (Glassdoor est.)
379    $110K-$163K (Glassdoor est.)
380    $110K-$163K (Glassdoor est.)
381    $110K-$163K (Glassdoor est.)
382    $110K-$163K (Glassdoor est.)
383    $110K-$163K (Glassdoor est.)
384    $110K-$163K (Glassdoor est.)
385    $110K-$163K (Glassdoor est.)
386    $110K-$163K (Glassdoor est.)
387    $110K-$163K (Glassdoor est.)
388    $110K-$163K (Glassdoor est.)
389    $110K-$163K (Glassdoor est.)
390    $110K-$163K (Glassdoor est.)
391    $110K-$163K (Glassdoor est.)
392    $110K-$163K (Glassdoor est.)
393    $110K-$163K (Glassdoor est.)
394    $110K-$163K (Glassdoor est.)
395    $110K-$163K (Glassdoor est.)
396    $110K-$163K (Glassdoor est.)
397    $110K-$163K (Glassdoor est.)
398    $124K-$198K (Glassdoor est.)
399    $124K-$198K (Glassdoor est.)
400    $124K-$198K (Glassdoor est.)
401    $124K-$198K (Glassdoor est.)
402    $124K-$198K (Glassdoor est.)
403    $124K-$198K (Glassdoor est.)
404    $124K-$198K (Glassdoor est.)
405    $124K-$198K (Glassdoor est.)
406    $124K-$198K (Glassdoor est.)
407    $124K-$198K (Glassdoor est.)
408    $124K-$198K (Glassdoor est.)
409    $124K-$198K (Glassdoor est.)
410    $124K-$198K (Glassdoor est.)
411    $124K-$198K (Glassdoor est.)
412    $124K-$198K (Glassdoor est.)
413    $124K-$198K (Glassdoor est.)
414    $124K-$198K (Glassdoor est.)
415    $124K-$198K (Glassdoor est.)
416    $124K-$198K (Glassdoor est.)
417    $124K-$198K (Glassdoor est.)
418    $124K-$198K (Glassdoor est.)
419     $79K-$133K (Glassdoor est.)
420     $79K-$133K (Glassdoor est.)
421     $79K-$133K (Glassdoor est.)
422     $79K-$133K (Glassdoor est.)
423     $79K-$133K (Glassdoor est.)
424     $79K-$133K (Glassdoor est.)
425     $79K-$133K (Glassdoor est.)
426     $79K-$133K (Glassdoor est.)
427     $79K-$133K (Glassdoor est.)
428     $79K-$133K (Glassdoor est.)
429     $79K-$133K (Glassdoor est.)
430     $79K-$133K (Glassdoor est.)
431     $79K-$133K (Glassdoor est.)
432     $79K-$133K (Glassdoor est.)
433     $79K-$133K (Glassdoor est.)
434     $79K-$133K (Glassdoor est.)
435     $79K-$133K (Glassdoor est.)
436     $79K-$133K (Glassdoor est.)
437     $79K-$133K (Glassdoor est.)
438     $69K-$116K (Glassdoor est.)
439     $69K-$116K (Glassdoor est.)
440     $69K-$116K (Glassdoor est.)
441     $69K-$116K (Glassdoor est.)
442     $69K-$116K (Glassdoor est.)
443     $69K-$116K (Glassdoor est.)
444     $69K-$116K (Glassdoor est.)
445     $69K-$116K (Glassdoor est.)
446     $69K-$116K (Glassdoor est.)
447     $69K-$116K (Glassdoor est.)
448     $69K-$116K (Glassdoor est.)
449     $69K-$116K (Glassdoor est.)
450     $69K-$116K (Glassdoor est.)
451     $69K-$116K (Glassdoor est.)
452     $69K-$116K (Glassdoor est.)
453     $69K-$116K (Glassdoor est.)
454     $69K-$116K (Glassdoor est.)
455     $69K-$116K (Glassdoor est.)
456     $69K-$116K (Glassdoor est.)
457     $69K-$116K (Glassdoor est.)
458     $69K-$116K (Glassdoor est.)
459      $31K-$56K (Glassdoor est.)
460      $31K-$56K (Glassdoor est.)
461      $31K-$56K (Glassdoor est.)
462      $31K-$56K (Glassdoor est.)
463      $31K-$56K (Glassdoor est.)
464      $31K-$56K (Glassdoor est.)
465      $31K-$56K (Glassdoor est.)
466      $31K-$56K (Glassdoor est.)
467      $31K-$56K (Glassdoor est.)
468      $31K-$56K (Glassdoor est.)
469      $31K-$56K (Glassdoor est.)
470      $31K-$56K (Glassdoor est.)
471      $31K-$56K (Glassdoor est.)
472      $31K-$56K (Glassdoor est.)
473      $31K-$56K (Glassdoor est.)
474      $31K-$56K (Glassdoor est.)
475      $31K-$56K (Glassdoor est.)
476      $31K-$56K (Glassdoor est.)
477      $31K-$56K (Glassdoor est.)
478      $31K-$56K (Glassdoor est.)
479     $95K-$119K (Glassdoor est.)
480     $95K-$119K (Glassdoor est.)
481     $95K-$119K (Glassdoor est.)
482     $95K-$119K (Glassdoor est.)
483     $95K-$119K (Glassdoor est.)
484     $95K-$119K (Glassdoor est.)
485     $95K-$119K (Glassdoor est.)
486     $95K-$119K (Glassdoor est.)
487     $95K-$119K (Glassdoor est.)
488     $95K-$119K (Glassdoor est.)
489     $95K-$119K (Glassdoor est.)
490     $95K-$119K (Glassdoor est.)
491     $95K-$119K (Glassdoor est.)
492     $95K-$119K (Glassdoor est.)
493     $95K-$119K (Glassdoor est.)
494     $95K-$119K (Glassdoor est.)
495    $212K-$331K (Glassdoor est.)
496    $212K-$331K (Glassdoor est.)
497    $212K-$331K (Glassdoor est.)
498    $212K-$331K (Glassdoor est.)
499    $212K-$331K (Glassdoor est.)
500    $212K-$331K (Glassdoor est.)
501    $212K-$331K (Glassdoor est.)
502    $212K-$331K (Glassdoor est.)
503    $212K-$331K (Glassdoor est.)
504    $212K-$331K (Glassdoor est.)
505    $212K-$331K (Glassdoor est.)
506    $212K-$331K (Glassdoor est.)
507    $212K-$331K (Glassdoor est.)
508    $212K-$331K (Glassdoor est.)
509    $212K-$331K (Glassdoor est.)
510    $212K-$331K (Glassdoor est.)
511    $212K-$331K (Glassdoor est.)
512    $212K-$331K (Glassdoor est.)
513    $212K-$331K (Glassdoor est.)
514    $212K-$331K (Glassdoor est.)
515    $212K-$331K (Glassdoor est.)
516     $66K-$112K (Glassdoor est.)
517     $66K-$112K (Glassdoor est.)
518     $66K-$112K (Glassdoor est.)
519     $66K-$112K (Glassdoor est.)
520     $66K-$112K (Glassdoor est.)
521     $66K-$112K (Glassdoor est.)
522     $66K-$112K (Glassdoor est.)
523     $66K-$112K (Glassdoor est.)
524     $66K-$112K (Glassdoor est.)
525     $66K-$112K (Glassdoor est.)
526     $66K-$112K (Glassdoor est.)
527     $66K-$112K (Glassdoor est.)
528     $66K-$112K (Glassdoor est.)
529     $66K-$112K (Glassdoor est.)
530     $66K-$112K (Glassdoor est.)
531     $66K-$112K (Glassdoor est.)
532     $66K-$112K (Glassdoor est.)
533     $66K-$112K (Glassdoor est.)
534     $66K-$112K (Glassdoor est.)
535     $66K-$112K (Glassdoor est.)
536    $128K-$201K (Glassdoor est.)
537    $128K-$201K (Glassdoor est.)
538    $128K-$201K (Glassdoor est.)
539    $128K-$201K (Glassdoor est.)
540    $128K-$201K (Glassdoor est.)
541    $128K-$201K (Glassdoor est.)
542    $128K-$201K (Glassdoor est.)
543    $128K-$201K (Glassdoor est.)
544    $128K-$201K (Glassdoor est.)
545    $128K-$201K (Glassdoor est.)
546    $128K-$201K (Glassdoor est.)
547    $128K-$201K (Glassdoor est.)
548    $128K-$201K (Glassdoor est.)
549    $128K-$201K (Glassdoor est.)
550    $128K-$201K (Glassdoor est.)
551    $128K-$201K (Glassdoor est.)
552    $128K-$201K (Glassdoor est.)
553    $128K-$201K (Glassdoor est.)
554    $128K-$201K (Glassdoor est.)

In [344]:
#2 formats:
#79K−131K (Glassdoor est.)
#145K−225K(Employer est.)

#remove (Glassdoor est.),(Employer est.)
dff = df['Salary Estimate'].str.strip(' (Glassdoor est.),(Employer est.)')
df.update(dff)
df['Salary Estimate']

0      $137K-$171K
1      $137K-$171K
2      $137K-$171K
3      $137K-$171K
4      $137K-$171K
5      $137K-$171K
6      $137K-$171K
7      $137K-$171K
8      $137K-$171K
9      $137K-$171K
10     $137K-$171K
11     $137K-$171K
12     $137K-$171K
13     $137K-$171K
14     $137K-$171K
15     $137K-$171K
16     $137K-$171K
17     $137K-$171K
18     $137K-$171K
19     $137K-$171K
20     $137K-$171K
21     $137K-$171K
22     $137K-$171K
23     $137K-$171K
24     $137K-$171K
25     $137K-$171K
26     $137K-$171K
27     $137K-$171K
28     $137K-$171K
29     $137K-$171K
30      $75K-$131K
31      $75K-$131K
32      $75K-$131K
33      $75K-$131K
34      $75K-$131K
35      $75K-$131K
36      $75K-$131K
37      $75K-$131K
38      $75K-$131K
39      $75K-$131K
40      $75K-$131K
41      $75K-$131K
42      $75K-$131K
43      $75K-$131K
44      $75K-$131K
45      $75K-$131K
46      $75K-$131K
47      $75K-$131K
48      $75K-$131K
49      $75K-$131K
50      $75K-$131K
51      $75K-$131K
52      $75K-$131K
53      $75K-$131K
54      $75K-$131K
55      $75K-$131K
56      $75K-$131K
57      $75K-$131K
58      $75K-$131K
59      $75K-$131K
60      $75K-$131K
61      $75K-$131K
62      $79K-$131K
63      $79K-$131K
64      $79K-$131K
65      $79K-$131K
66      $79K-$131K
67      $79K-$131K
68      $79K-$131K
69      $79K-$131K
70      $79K-$131K
71      $79K-$131K
72      $79K-$131K
73      $79K-$131K
74      $79K-$131K
75      $79K-$131K
76      $79K-$131K
77      $79K-$131K
78      $79K-$131K
79      $79K-$131K
80      $79K-$131K
81      $79K-$131K
82      $79K-$131K
83      $79K-$131K
84      $79K-$131K
85      $79K-$131K
86      $79K-$131K
87      $79K-$131K
88      $79K-$131K
89      $79K-$131K
90      $79K-$131K
91      $79K-$131K
92      $79K-$131K
93      $79K-$131K
94      $99K-$132K
95      $99K-$132K
96      $99K-$132K
97      $99K-$132K
98      $99K-$132K
99      $99K-$132K
100     $99K-$132K
101     $99K-$132K
102     $99K-$132K
103     $99K-$132K
104     $99K-$132K
105     $99K-$132K
106     $99K-$132K
107     $99K-$132K
108     $99K-$132K
109     $99K-$132K
110     $99K-$132K
111     $99K-$132K
112     $99K-$132K
113     $99K-$132K
114     $99K-$132K
115     $99K-$132K
116     $99K-$132K
117     $99K-$132K
118     $99K-$132K
119     $99K-$132K
120     $99K-$132K
121     $99K-$132K
122     $99K-$132K
123     $99K-$132K
124     $99K-$132K
125     $99K-$132K
126     $90K-$109K
127     $90K-$109K
128     $90K-$109K
129     $90K-$109K
130     $90K-$109K
131     $90K-$109K
132     $90K-$109K
133     $90K-$109K
134     $90K-$109K
135     $90K-$109K
136     $90K-$109K
137     $90K-$109K
138     $90K-$109K
139     $90K-$109K
140     $90K-$109K
141     $90K-$109K
142     $90K-$109K
143     $90K-$109K
144     $90K-$109K
145     $90K-$109K
146     $90K-$109K
147     $90K-$109K
148     $90K-$109K
149     $90K-$109K
150     $90K-$109K
151     $90K-$109K
152     $90K-$109K
153     $90K-$109K
154    $101K-$165K
155    $101K-$165K
156    $101K-$165K
157    $101K-$165K
158    $101K-$165K
159    $101K-$165K
160    $101K-$165K
161    $101K-$165K
162    $101K-$165K
163    $101K-$165K
164    $101K-$165K
165    $101K-$165K
166    $101K-$165K
167    $101K-$165K
168    $101K-$165K
169    $101K-$165K
170    $101K-$165K
171    $101K-$165K
172    $101K-$165K
173    $101K-$165K
174    $101K-$165K
175      $56K-$97K
176      $56K-$97K
177      $56K-$97K
178      $56K-$97K
179      $56K-$97K
180      $56K-$97K
181      $56K-$97K
182      $56K-$97K
183      $56K-$97K
184      $56K-$97K
185      $56K-$97K
186      $56K-$97K
187      $56K-$97K
188      $56K-$97K
189      $56K-$97K
190      $56K-$97K
191      $56K-$97K
192      $56K-$97K
193      $56K-$97K
194      $56K-$97K
195      $56K-$97K
196      $56K-$97K
197     $79K-$106K
198     $79K-$106K
199     $79K-$106K
200     $79K-$106K
201     $79K-$106K
202     $79K-$106K
203     $79K-$106K
204     $79K-$106K
205     $79K-$106K
206     $79K-$106K
207     $79K-$106K
208     $79K-$106K
209     $79K-$106K
210     $79K-$106K
211     $79K-$106K
212     $79K-$106K
213     $79K-$106K
214     $79K-$106K
215     $79K-$106K
216     $79K-$106K
217     $79K-$106K
218     $79K-$106K
219     $71K-$123K
220     $71K-$123K
221     $71K-$123K
222     $71K-$123K
223     $71K-$123K
224     $71K-$123K
225     $71K-$123K
226     $71K-$123K
227     $71K-$123K
228     $71K-$123K
229     $71K-$123K
230     $71K-$123K
231     $71K-$123K
232     $71K-$123K
233     $71K-$123K
234     $71K-$123K
235     $71K-$123K
236     $71K-$123K
237     $71K-$123K
238     $90K-$124K
239     $90K-$124K
240     $90K-$124K
241     $90K-$124K
242     $90K-$124K
243     $90K-$124K
244     $90K-$124K
245     $90K-$124K
246     $90K-$124K
247     $90K-$124K
248     $90K-$124K
249     $90K-$124K
250     $90K-$124K
251     $90K-$124K
252     $90K-$124K
253     $90K-$124K
254     $90K-$124K
255     $90K-$124K
256     $90K-$124K
257     $90K-$124K
258     $90K-$124K
259     $90K-$124K
260     $91K-$150K
261     $91K-$150K
262     $91K-$150K
263     $91K-$150K
264     $91K-$150K
265     $91K-$150K
266     $91K-$150K
267     $91K-$150K
268     $91K-$150K
269     $91K-$150K
270     $91K-$150K
271     $91K-$150K
272     $91K-$150K
273     $91K-$150K
274     $91K-$150K
275     $91K-$150K
276     $91K-$150K
277     $91K-$150K
278     $91K-$150K
279     $91K-$150K
280     $91K-$150K
281    $141K-$225K
282    $141K-$225K
283    $141K-$225K
284    $141K-$225K
285    $141K-$225K
286    $141K-$225K
287    $141K-$225K
288    $141K-$225K
289    $141K-$225K
290    $141K-$225K
291    $141K-$225K
292    $141K-$225K
293    $141K-$225K
294    $141K-$225K
295    $141K-$225K
296    $141K-$225K
297    $141K-$225K
298    $141K-$225K
299    $141K-$225K
300    $141K-$225K
301    $145K-$225K
302    $145K-$225K
303    $145K-$225K
304    $145K-$225K
305    $145K-$225K
306    $145K-$225K
307    $145K-$225K
308    $145K-$225K
309    $145K-$225K
310    $145K-$225K
311    $145K-$225K
312    $145K-$225K
313    $145K-$225K
314    $145K-$225K
315    $145K-$225K
316    $145K-$225K
317    $145K-$225K
318    $145K-$225K
319    $145K-$225K
320    $145K-$225K
321     $79K-$147K
322     $79K-$147K
323     $79K-$147K
324     $79K-$147K
325     $79K-$147K
326     $79K-$147K
327     $79K-$147K
328     $79K-$147K
329     $79K-$147K
330     $79K-$147K
331     $79K-$147K
332     $79K-$147K
333     $79K-$147K
334     $79K-$147K
335     $79K-$147K
336     $79K-$147K
337     $79K-$147K
338     $79K-$147K
339     $79K-$147K
340     $79K-$147K
341    $122K-$146K
342    $122K-$146K
343    $122K-$146K
344    $122K-$146K
345    $122K-$146K
346    $122K-$146K
347    $122K-$146K
348    $122K-$146K
349    $122K-$146K
350    $122K-$146K
351    $122K-$146K
352    $122K-$146K
353    $122K-$146K
354    $122K-$146K
355    $122K-$146K
356    $122K-$146K
357    $112K-$116K
358    $112K-$116K
359    $112K-$116K
360    $112K-$116K
361    $112K-$116K
362    $112K-$116K
363    $112K-$116K
364    $112K-$116K
365    $112K-$116K
366    $112K-$116K
367    $112K-$116K
368    $112K-$116K
369    $112K-$116K
370    $112K-$116K
371    $112K-$116K
372    $112K-$116K
373    $112K-$116K
374    $112K-$116K
375    $112K-$116K
376    $112K-$116K
377    $112K-$116K
378    $110K-$163K
379    $110K-$163K
380    $110K-$163K
381    $110K-$163K
382    $110K-$163K
383    $110K-$163K
384    $110K-$163K
385    $110K-$163K
386    $110K-$163K
387    $110K-$163K
388    $110K-$163K
389    $110K-$163K
390    $110K-$163K
391    $110K-$163K
392    $110K-$163K
393    $110K-$163K
394    $110K-$163K
395    $110K-$163K
396    $110K-$163K
397    $110K-$163K
398    $124K-$198K
399    $124K-$198K
400    $124K-$198K
401    $124K-$198K
402    $124K-$198K
403    $124K-$198K
404    $124K-$198K
405    $124K-$198K
406    $124K-$198K
407    $124K-$198K
408    $124K-$198K
409    $124K-$198K
410    $124K-$198K
411    $124K-$198K
412    $124K-$198K
413    $124K-$198K
414    $124K-$198K
415    $124K-$198K
416    $124K-$198K
417    $124K-$198K
418    $124K-$198K
419     $79K-$133K
420     $79K-$133K
421     $79K-$133K
422     $79K-$133K
423     $79K-$133K
424     $79K-$133K
425     $79K-$133K
426     $79K-$133K
427     $79K-$133K
428     $79K-$133K
429     $79K-$133K
430     $79K-$133K
431     $79K-$133K
432     $79K-$133K
433     $79K-$133K
434     $79K-$133K
435     $79K-$133K
436     $79K-$133K
437     $79K-$133K
438     $69K-$116K
439     $69K-$116K
440     $69K-$116K
441     $69K-$116K
442     $69K-$116K
443     $69K-$116K
444     $69K-$116K
445     $69K-$116K
446     $69K-$116K
447     $69K-$116K
448     $69K-$116K
449     $69K-$116K
450     $69K-$116K
451     $69K-$116K
452     $69K-$116K
453     $69K-$116K
454     $69K-$116K
455     $69K-$116K
456     $69K-$116K
457     $69K-$116K
458     $69K-$116K
459      $31K-$56K
460      $31K-$56K
461      $31K-$56K
462      $31K-$56K
463      $31K-$56K
464      $31K-$56K
465      $31K-$56K
466      $31K-$56K
467      $31K-$56K
468      $31K-$56K
469      $31K-$56K
470      $31K-$56K
471      $31K-$56K
472      $31K-$56K
473      $31K-$56K
474      $31K-$56K
475      $31K-$56K
476      $31K-$56K
477      $31K-$56K
478      $31K-$56K
479     $95K-$119K
480     $95K-$119K
481     $95K-$119K
482     $95K-$119K
483     $95K-$119K
484     $95K-$119K
485     $95K-$119K
486     $95K-$119K
487     $95K-$119K
488     $95K-$119K
489     $95K-$119K
490     $95K-$119K
491     $95K-$119K
492     $95K-$119K
493     $95K-$119K
494     $95K-$119K
495    $212K-$331K
496    $212K-$331K
497    $212K-$331K
498    $212K-$331K
499    $212K-$331K
500    $212K-$331K
501    $212K-$331K
502    $212K-$331K
503    $212K-$331K
504    $212K-$331K
505    $212K-$331K
506    $212K-$331K
507    $212K-$331K
508    $212K-$331K
509    $212K-$331K
510    $212K-$331K
511    $212K-$331K
512    $212K-$331K
513    $212K-$331K
514    $212K-$331K
515    $212K-$331K
516     $66K-$112K
517     $66K-$112K
518     $66K-$112K
519     $66K-$112K
520     $66K-$112K
521     $66K-$112K
522     $66K-$112K
523     $66K-$112K
524     $66K-$112K
525     $66K-$112K
526     $66K-$112K
527     $66K-$112K
528     $66K-$112K
529     $66K-$112K
530     $66K-$112K
531     $66K-$112K
532     $66K-$112K
533     $66K-$112K
534     $66K-$112K
535     $66K-$112K
536    $128K-$201K
537    $128K-$201K
538    $128K-$201K
539    $128K-$201K
540    $128K-$201K
541    $128K-$201K
542    $128K-$201K
543    $128K-$201K
544    $128K-$201K
545    $128K-$201K
546    $128K-$201K
547    $128K-$201K
548    $128K-$201K
549    $128K-$201K
550    $128K-$201K
551    $128K-$201K
552    $128K-$201K
553    $128K-$201K
554    $128K-$201K
555    $128K-$201K
556    $128K-$201K
557    $138K-$158K
558    $138K-$158K
559    $138K-$158K
560    $138K-$158K
561    $138K-$158K
562    $138K-$158K
563    $138K-$158K
564    $138K-$158K
565    $138K-$158K
566    $138K-$158K
567    $138K-$158K
568    $138K-$158K
569    $138K-$158K
570    $138K-$158K
571    $138K-$158K
572    $138K-$158K
573    $138K-$158K
574    $138K-$158K
575    $138K-$158K
576    $138K-$158K
577    $138K-$158K
578     $80K-$132K
579     $80K-$132K
580     $80K-$132K
581     $80K-$132K
582     $80K-$132K
583     $80K-$132K
584     $80K-$132K
585     $80K-$132K
586     $80K-$132K
587     $80K-$132K
588     $80K-$132K
589     $80K-$132K
590     $80K-$132K
591     $80K-$132K
592     $80K-$132K
593     $80K-$132K
594     $80K-$132K
595     $80K-$132K
596     $80K-$132K
597     $80K-$132K
598     $87K-$141K
599     $87K-$141K
600     $87K-$141K
601     $87K-$141K
602     $87K-$141K
603     $87K-$141K
604     $87K-$141K
605     $87K-$141K
606     $87K-$141K
607     $87K-$141K
608     $87K-$141K
609     $87K-$141K
610     $87K-$141K
611     $87K-$141K
612     $87K-$141K
613     $87K-$141K
614     $87K-$141K
615     $87K-$141K
616     $87K-$141K
617     $87K-$141K
618     $92K-$155K
619     $92K-$155K
620     $92K-$155K
621     $92K-$155K
622     $92K-$155K
623     $92K-$155K
624     $92K-$155K
625     $92K-$155K
626     $92K-$155K
627     $92K-$155K
628     $92K-$155K
629     $92K-$155K
630     $92K-$155K
631     $92K-$155K
632     $92K-$155K
633     $92K-$155K
634     $92K-$155K
635     $92K-$155K
636     $92K-$155K
637     $92K-$155K
638     $92K-$155K
639    $105K-$167K
640    $105K-$167K
641    $105K-$167K
642    $105K-$167K
643    $105K-$167K
644    $105K-$167K
645    $105K-$167K
646    $105K-$167K
647    $105K-$167K
648    $105K-$167K
649    $105K-$167K
650    $105K-$167K
651    $105K-$167K
652    $105K-$167K
653    $105K-$167K
654    $105K-$167K
655    $105K-$167K
656    $105K-$167K
657    $105K-$167K
658    $105K-$167K
Name: Salary Estimate, dtype: object

In [345]:
#add min salary , max salary and average salary
df['Min_Salary'] =  df['Salary Estimate'].str.split('-').str[0].str.strip('$K').astype(int)
df['Max_Salary'] =  df['Salary Estimate'].str.split('-').str[1].str.strip('$K').astype(int)
df['AVG_Salary'] = df[['Min_Salary','Max_Salary']].mean(axis = 1)

#Convert from 'Salary Estimate' column to format: 'Min_salary - Max_Salary'
df['Salary Estimate'] = df['Min_Salary'].astype(str) + '-' + df['Max_Salary'].astype(str)
df.rename({'Salary Estimate':'Salary Estimate(K$)'}, axis = 1, inplace = True)
df.head()

,index,Job Title,Salary Estimate(K$),Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,State,Min_Salary,Max_Salary,AVG_Salary
0,1,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",NY,137,171,154.0
1,2,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,VA,137,171,154.0
2,3,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,MA,137,171,154.0
3,4,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",MA,137,171,154.0
4,5,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",NY,137,171,154.0

### Calculate Age of Company

In [346]:
df['Company_Age'] = df['Founded'].apply(lambda x: 'unknown' if x == -1 else 2023 - x)
df['Company_Age']

0           30
1           55
2           42
3           23
4           25
5           13
6           27
7           33
8           40
9            9
10          11
11           7
12          58
13          50
14          37
15          26
16           8
17          78
18          35
19           6
20           8
21          12
22          56
23         163
24          31
25          20
26          27
27          72
28          18
29           8
30          42
31          27
32           4
33          98
34          15
35          24
36          45
37          23
38          23
39          57
40          50
41         111
42          65
43           4
44          10
45         174
46          11
47          23
48           7
49          24
50           9
51         242
52          11
53          20
54          24
55          97
56          11
57          17
58          12
59          29
60         160
61          13
62          33
63          13
64          37
65          28
66          11
67          17
68           8
69     unknown
70          17
71           8
72          41
73          98
74          49
75          22
76          30
77           4
78          38
79          20
80         110
81          22
82          27
83           7
84          24
85          13
86          52
87          20
88          11
89         112
90         110
91          24
92          55
93          26
94          37
95          40
96           8
97         112
98          14
99          64
100         10
101         16
102         11
103         41
104         40
105         50
106         42
107         12
108         84
109         10
110         56
111         10
112    unknown
113          7
114         27
115          7
116         21
117         56
118          4
119         23
120         17
121          8
122         11
123         17
124         17
125         27
126          7
127          9
128         17
129         27
130          7
131         12
132         20
133         11
134          8
135         11
136         29
137         11
138         26
139         22
140         10
141         65
142         10
143         10
144         41
145         17
146         23
147         56
148          7
149         62
150         21
151         28
152    unknown
153         60
154         11
155         26
156    unknown
157         54
158         17
159         77
160    unknown
161         26
162         27
163          8
164         41
165         55
166         66
167         20
168         77
169          8
170         14
171          9
172         70
173          8
174         25
175         58
176         78
177         56
178         10
179         26
180         75
181        173
182         15
183        172
184         19
185         47
186         13
187         28
188         24
189         12
190        110
191    unknown
192        110
193    unknown
194        105
195         10
196         31
197          8
198         31
199         15
200         69
201         15
202         27
203         22
204         11
205         24
206         27
207         12
208         33
209    unknown
210         12
211         11
212         76
213        110
214         13
215         27
216        172
217          8
218         68
219         12
220         27
221         25
222          9
223         15
224         24
225          5
226         56
227         86
228    unknown
229         10
230        173
231          6
232         75
233         52
234    unknown
235         25
236         15
237    unknown
238         20
239         98
240         23
241         17
242         14
243         50
244         12
245         23
246    unknown
247         40
248        172
249    unknown
250        106
251         88
252         16
253         14
254         94
255         13
256    unknown
257         25
258         24
259         28
260         72
261         24
262         58
263         42
264        203
265         13
266         28
267          5
268         12
269         42
270         60
271         12
272    unknown
273         71
274         91
275         76
276         11
277        129
278         18
279          5
280    unknown
281         57
282          4
283    unknown
284        110
285        106
286    unknown
287         63
288    unknown
289         17
290         54
291         30
292    unknown
293    unknown
294          6
295          6
296         33
297         16
298        235
299         23
300         31
301          8
302         18
303         10
304         19
305    unknown
306    unknown
307         20
308          8
309        105
310         10
311         31
312         12
313         18
314    unknown
315         23
316         31
317    unknown
318    unknown
319        193
320    unknown
321          7
322         23
323         15
324         26
325         28
326         39
327    unknown
328         69
329         90
330         23
331         20
332         27
333    unknown
334        143
335         24
336    unknown
337         39
338         37
339         12
340         11
341         11
342         10
343         24
344        136
345         53
346    unknown
347          9
348         21
349    unknown
350         81
351         13
352         21
353         12
354         11
355    unknown
356    unknown
357         24
358        242
359    unknown
360         76
361         15
362         11
363        110
364    unknown
365          5
366         43
367         20
368         34
369         22
370         12
371         24
372        115
373         27
374        172
375         20
376        170
377         12
378         11
379         14
380         45
381    unknown
382          8
383         42
384    unknown
385         18
386          8
387        111
388         27
389    unknown
390         49
391         13
392         11
393         90
394         28
395         29
396        148
397          7
398         17
399         12
400         13
401    unknown
402          5
403         18
404    unknown
405    unknown
406    unknown
407          9
408         24
409        109
410        125
411         13
412         75
413         31
414    unknown
415         18
416    unknown
417    unknown
418         15
419         11
420         11
421    unknown
422    unknown
423    unknown
424         15
425    unknown
426         67
427    unknown
428          5
429    unknown
430    unknown
431          9
432    unknown
433    unknown
434         16
435         46
436          4
437         23
438         29
439         41
440    unknown
441         27
442         16
443         14
444        112
445         16
446         14
447        143
448         17
449    unknown
450         39
451    unknown
452         55
453         14
454    unknown
455         37
456    unknown
457         12
458         34
459          8
460         17
461         11
462         24
463         19
464         53
465         11
466        136
467         23
468    unknown
469         36
470    unknown
471         27
472         21
473         25
474         28
475         38
476         81
477         13
478         12
479          8
480          4
481         13
482    unknown
483         11
484         33
485         54
486    unknown
487    unknown
488         35
489         24
490    unknown
491    unknown
492         29
493         25
494         12
495        127
496        110
497         21
498         36
499    unknown
500    unknown
501    unknown
502    unknown
503         76
504         13
505         11
506    unknown
507    unknown
508         13
509         11
510         76
511    unknown
512         43
513         20
514         47
515         11
516          7
517         22
518    unknown
519         22
520         14
521         37
522         47
523         57
524         12
525         13
526         11
527         24
528        115
529         76
530         17
531        172
532    unknown
533         11
534         26
535        170
536         20
537         24
538         14
539         12
540         15
541         45
542    unknown
543          8
544         51
545         27
546         19
547         18
548          6
549         49
550         41
551          8
552         47
553         27
554    unknown
555    unknown
556         65
557        112
558         20
559         52
560    unknown
561         49
562         13
563         11
564    unknown
565         90
566    unknown
567         10
568         90
569        148
570         65
571          7
572    unknown
573         31
574         27
575         25
576         74
577    unknown
578        110
579         41
580         25
581        193
582         76
583         15
584         14
585    unknown
586         18
587         38
588         19
589         81
590         12
591         13
592    unknown
593         26
594         24
595    unknown
596         38
597    unknown
598         26
599         55
600    unknown
601        170
602    unknown
603         40
604         24
605         14
606         17
607         72
608    unknown
609         10
610         25
611         33
612         11
613         27
614         35
615         23
616         29
617         19
618        112
619         10
620    unknown
621         69
622         25
623         12
624    unknown
625    unknown
626         24
627         36
628    unknown
629         31
630         49
631         61
632         47
633    unknown
634         76
635         15
636         11
637    unknown
638        110
639         14
640         27
641         13
642    unknown
643    unknown
644    unknown
645         13
646          5
647    unknown
648    unknown
649    unknown
650         19
651    unknown
652         18
653         13
654         34
655    unknown
656    unknown
657    unknown
658         47
Name: Company_Age, dtype: object

### Extracting key skills mentioned in the job description

In [347]:
def key_skills(key_skill):
    df[key_skill] = df['Job Description'].apply(lambda x: 1 if key_skill in x.lower() else 0)
    
key_skills('python')
key_skills('excel')
key_skills('hadoop')
key_skills('spark')
key_skills('aws')
key_skills('tableau')
key_skills('big_data')
df.head()

,index,Job Title,Salary Estimate(K$),Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,State,Min_Salary,Max_Salary,AVG_Salary,Company_Age,python,excel,hadoop,spark,aws,tableau,big_data
0,1,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",NY,137,171,154.0,30,0,0,0,0,1,0,0
1,2,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,VA,137,171,154.0,55,0,0,1,0,0,0,0
2,3,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,MA,137,171,154.0,42,1,1,0,0,1,0,0
3,4,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",MA,137,171,154.0,23,1,1,0,0,1,0,0
4,5,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",NY,137,171,154.0,25,1,1,0,0,0,0,0

### Create seniority column from Job Title Column

In [348]:
df['Job Title'].value_counts().to_frame()

                                                    Job Title
Data Scientist                                            326
Data Engineer                                              26
Senior Data Scientist                                      19
Machine Learning Engineer                                  15
Data Analyst                                               12
Senior Data Analyst                                         6
Data Scientist - TS/SCI FSP or CI Required                  4
Data Science Software Engineer                              4
ENGINEER - COMPUTER SCIENTIST - RESEARCH COMPUT...          4
Senior Data Engineer                                        4
Data Scientist - TS/SCI Required                            3
Analytics - Business Assurance Data Analyst                 3
Sr. ML/Data Scientist - AI/NLP/Chatbot                      3
Senior Business Intelligence Analyst                        3
AI Ops Data Scientist                                       3
Principal Data Scientist                                    3
Decision Scientist                                          3
Senior Data Scientist – Image Analytics, Novart...          3
Data Modeler (Analytical Systems)                           3
Lead Data Scientist                                         3
Senior Machine Learning Scientist - Bay Area, CA            3
In-Line Inspection Data Analyst                             2
Computer Vision / Deep Learning Scientist                   2
Principal Scientist/Associate Director, Quality...          2
Senior Machine Learning Engineer                            2
Senior Data Scientist - R&D Oncology                        2
Principal Machine Learning Scientist                        2
Principal Data Scientist - Machine Learning                 2
Computational Behavioral Scientist                          2
Sr. Data Scientist II                                       2
Research Scientist - Patient-Centered Research ...          2
Scientist / Group Lead, Cancer Biology                      2
Data Scientist(s)/Machine Learning Engineer                 2
Cloud Data Engineer (Azure)                                 2
Senior Scientist - Toxicologist - Product Integ...          2
IT Partner Digital Health Technology and Data S...          2
Intelligence Data Analyst, Senior                           2
Analytics Manager - Data Mart                               2
Machine Learning Engineer/Scientist                         2
Data Analyst - Unilever Prestige                            2
Applied Computer Scientist                                  2
Weapons and Sensors Engineer/Scientist                      2
VP, Data Science                                            2
Data Engineer - Kafka                                       2
Data Scientist (TS/SCI w/ Poly)                             2
Scientist - Machine Learning                                2
Sr. Data Scientist                                          2
Data Engineer (Analytics, SQL, Python, AWS)                 2
Senior Data Analyst - Finance & Platform Analytics          2
Sr Data Scientist                                           2
Health Plan Data Analyst, Sr                                2
Data Scientist - Image and Video Analytics                  2
Data & Machine Learning Scientist                           2
Product Data Scientist - Ads Data Science                   2
Data Scientist - Intermediate                               2
Data Scientist / Machine Learning Expert                    2
(Sr.) Data Scientist -                                      2
Staff Data Scientist - Analytics                            2
Patient Safety- Associate Data Scientist                    2
Data Scientist - Machine Learning                           2
Data Analytics Engineer                                     2
Data Scientist / Applied Mathematician                      2
Data Scientist - Statistics, Early Career                   2
Data Scientist - Contract                                   2
Real World Science, Data Scientist                          2
Data Scientist 3 (718)                                      2
Data Scientist, Applied Machine Learning - Bay ...          2
Data Scientist, Kinship - NYC/Portland                      2
Experienced Data Scientist                                  2
Data Scientist-Human Resources                              2
Data Scientist/Machine Learning                             2
Senior Analyst/Data Scientist                               2
Business Intelligence Analyst                               2
Associate Data Scientist                                    2
Data Scientist - Risk                                       2
Senior Research Statistician- Data Scientist                2
Data Solutions Engineer - Data Modeler                      1
Scientist - Molecular Biology                               1
Data Analyst I                                              1
Data Science All Star Program - Data Engineer T...          1
Applied AI Scientist / Engineer                             1
Lead Certified Clinical Laboratory Scientist - ...          1
Business Intelligence Analyst I- Data Insights              1
Market Research Data Scientist                              1
Data Analyst II                                             1
Human Factors Scientist                                     1
Software Engineer (Data Scientist, C,C++,Linux,...          1
Senior Clinical Data Scientist Programmer                   1
Medical Lab Scientist                                       1
Sr Data Engineer (Sr BI Developer)                          1
Sr. Data Analyst                                            1
Data Modeler                                                1
Data Scientist/Data Analytics Practitioner                  1
Hydrogen/Tritium Materials Scientist (Experienced)          1
Developer III - Data Science                                1
Sr. Research Associate/ Scientist, NGS prep & M...          1
Lead Data Scientist – Network Analysis and Control          1
Enterprise Data Analyst (Enterprise Portfolio M...          1
Vice President, Biometrics and Clinical Data Ma...          1
Scientist/Research Associate-Metabolic Engineering          1
Information Systems Engineering Specialist (Eng...          1
Machine Learning Engineer, Sr.                              1
Aviation AI/ML Data Scientist                               1
Data Architect                                              1
Big Data Engineer                                           1
Data Science Manager                                        1
Data Scientist Technical Specialist                         1
Clinical Data Analyst                                       1
Software Engineer - Machine Learning & Data Sci...          1
COMPUTER SCIENTIST - ENGINEER - RESEARCH COMPUT...          1
Data Science Analyst                                        1
Machine Learning Scientist / Engineer                       1
COMPUTER SCIENTIST - ENGINEER - RESEARCH COMPUT...          1
Manager, Field Application Scientist, Southeast             1
Senior Principal Data Scientist (Python/R)                  1
Data Scientist- Industrial Discrete Sector Indu...          1
Development Scientist, Voltaren                             1
Principal Data & Analytics Platform Engineer                1
Data Scientist - Statistics, Mid-Career                     1
Chief Scientist                                             1
Production Engineer - Statistics/Data Analysis              1
Senior Data & Machine Learning Scientist                    1
Senior Data Scientist - Algorithms                          1
Machine Learning Scientist - Bay Area, CA                   1
Sr Data Analyst                                             1
Computational Scientist                                     1
Geospatial Data Scientist                                   1
Say Business Data Analyst                                   1
ELISA RESEARCH SCIENTIST (CV-15)                            1
Sr Scientist - Extractables & Leachables                    1
Staff Scientist- Upstream PD                                1
Analytics Manager                                           1
Scientist - Biomarker and Flow Cytometry                    1
Research Scientist Patient Preferences (Remote)             1
AI Data Scientist                                           1
Tableau Data Engineer 20-0117                               1
Data Integration and Modeling Engineer                      1
Applied Technology Researcher / Data Scientist              1
Health Data Scientist - Biomedical/Biostats                 1
NGS Scientist                                               1
Data Analyst/Engineer                                       1
Software Engineer - Data Science                            1
Data Scientist (TS/SCI)                                     1
RFP Data Analyst                                            1
Jr. Business Data Analyst (position added 6/12/...          1
Statistical Scientist                                       1
Data Scientist Machine Learning                             1
Data Science Manager, Payment Acceptance - USA              1
Diversity and Inclusion Data Analyst                        1
Manager / Lead, Data Science & Analytics                    1
Data Engineer, Digital & Comp Pathology                     1
Director of Data Science                                    1
Staff Data Scientist                                        1
Staff BI and Data Engineer                                  1
Environmental Data Science                                  1
Computer Scientist 1                                        1
Real World Evidence (RWE) Scientist                         1
Software Data Engineer                                      1
Operations Data Analyst                                     1
Equity Data Insights Analyst - Quantitative Ana...          1
Staff Data Scientist - Pricing                              1
Report Writer-Data Analyst                                  1
Computational Scientist, Machine Learning                   1
Jr. Data Engineer                                           1
E-Commerce Data Analyst                                     1
Global Data Analyst                                         1
Data Engineer (Remote)                                      1
Data Science Instructor                                     1
Business Data Analyst                                       1
Purification Scientist                                      1
Data Engineer, Enterprise Analytics                         1
AI/ML - Machine Learning Scientist, Siri Unders...          1

In [349]:
def seniority(job_title):
    job_title=job_title.lower()
    senior=['sr','senior','lead','principal','vp','vice president','director']
    for i in senior:
        if i in job_title:
            return "senior"
    if "jr" in job_title:
        return "junior"
    return "all level"

df['Seniority'] = df['Job Title'].apply(seniority)
df['Seniority'].value_counts().to_frame()

           Seniority
all level        560
senior            97
junior             2

In [350]:
#select rows where Seniority = 'senior'
df[df['Seniority'] == 'senior']

,index,Job Title,Salary Estimate(K$),Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,State,Min_Salary,Max_Salary,AVG_Salary,Company_Age,python,excel,hadoop,spark,aws,tableau,big_data,Seniority
0,1,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",NY,137,171,154.0,30,0,0,0,0,1,0,0,senior
33,34,Senior Research Statistician- Data Scientist,75-131,Acuity is seeking a Senior Research Statistici...,4.8,Acuity Insurance,"Sheboygan, WI","Sheboygan, WI",1001 to 5000 employees,1925,Company - Private,Insurance Carriers,Insurance,$1 to $2 billion (USD),-1,WI,75,131,103.0,98,0,0,0,0,0,0,0,senior
39,40,Senior Analyst/Data Scientist,75-131,At Edmunds were driven to make car buying easi...,3.4,Edmunds.com,"Santa Monica, CA","Santa Monica, CA",501 to 1000 employees,1966,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"TrueCar, Cars.com, Kelley Blue Book",CA,75,131,103.0,57,1,1,0,0,1,1,0,senior
46,47,Senior Data Scientist,75-131,Klaviyo is looking for Senior Data Scientists ...,4.8,Klaviyo,"Boston, MA","Boston, MA",201 to 500 employees,2012,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1,MA,75,131,103.0,11,0,0,0,0,0,0,0,senior
56,57,Senior Data Scientist,75-131,Benson Hill empowers innovators to develop mor...,3.5,Benson Hill,"Saint Louis, MO","Saint Louis, MO",201 to 500 employees,2012,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $5 million (USD),-1,MO,75,131,103.0,11,1,1,0,0,0,0,0,senior
72,73,Principal Data Scientist,79-131,Job Requisition ID #\n20WD40121\nJob Title\nPr...,4.0,Autodesk,"San Francisco, CA","San Rafael, CA",5001 to 10000 employees,1982,Company - Public,Computer Hardware & Software,Information Technology,$2 to $5 billion (USD),-1,CA,79,131,105.0,41,1,1,1,1,1,0,0,senior
92,93,Senior Data Scientist,79-131,"Secure our Nation, Ignite your Future\n\nJob S...",4.2,ManTech,"Alexandria, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,VA,79,131,105.0,55,1,0,1,1,0,1,0,senior
93,94,(Sr.) Data Scientist -,79-131,"Thursday, June 11, 2020\n\nMerrick Bank is a t...",3.6,Merrick Bank,Utah,"South Jordan, UT",201 to 500 employees,1997,Company - Private,Banks & Credit Unions,Finance,Unknown / Non-Applicable,-1,UT,79,131,105.0,26,1,1,0,0,1,0,0,senior
98,99,Senior Data Scientist,99-132,"About Us\n\nAt GutCheck, we pioneered agile ma...",3.8,GutCheck,"Denver, CO","Denver, CO",51 to 200 employees,2009,Company - Private,Advertising & Marketing,Business Services,$10 to $25 million (USD),"Nielsen, Zappi, SurveyMonkey",CO,99,132,115.5,14,0,0,0,0,0,0,0,senior
103,104,Senior Data Scientist,99-132,Job Requisition ID #\n20WD40666\nJob Title\nSe...,4.0,Autodesk,"San Francisco, CA","San Rafael, CA",5001 to 10000 employees,1982,Company - Public,Computer Hardware & Software,Information Technology,$2 to $5 billion (USD),-1,CA,99,132,115.5,41,1,0,1,1,0,0,0,senior
106,107,Sr Data Engineer (Sr BI Developer),99-132,Description/Responsibilities\n\n\nResponsible ...,3.2,Tivity Health,"Chandler, AZ","Franklin, TN",501 to 1000 employees,1981,Company - Public,Health Care Services & Hospitals,Health Care,Unknown / Non-Applicable,-1,AZ,99,132,115.5,42,0,0,1,0,0,0,0,senior
108,109,Lead Data Scientist,99-132,Applies advanced subject matter knowledge to s...,4.1,HP Inc.,"San Diego, CA","Palo Alto, CA",10000+ employees,1939,Company - Public,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1,CA,99,132,115.5,84,1,1,1,0,1,0,0,senior
121,122,Senior Data Engineer,99-132,About Scoop\n\nScoop brings co-workers and nei...,4.7,Scoop,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2015,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,-1,CA,99,132,115.5,8,1,0,0,1,0,0,0,senior
122,123,Senior Data Scientist,99-132,Join our team dedicated to developing and exec...,4.5,Novetta,"Herndon, VA","Mc Lean, VA",501 to 1000 employees,2012,Company - Private,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"Leidos, CACI International, Booz Allen Hamilton",VA,99,132,115.5,11,1,1,0,0,1,0,0,senior
125,126,Sr. ML/Data Scientist - AI/NLP/Chatbot,99-132,Sr. ML/Data Scientist - AI/NLP/Chatbot\n\nMist...,3.8,Juniper Networks,"Cupertino, CA","Sunnyvale, CA",5001 to 10000 employees,1996,Company - Public,Telecommunications Services,Telecommunications,$2 to $5 billion (USD),-1,CA,99,132,115.5,27,1,1,0,1,1,0,0,senior
129,130,Sr. ML/Data Scientist - AI/NLP/Chatbot,90-109,Sr. ML/Data Scientist - AI/NLP/Chatbot\n\nMist...,3.8,Juniper Networks,"Cupertino, CA","Sunnyvale, CA",5001 to 10000 employees,1996,Company - Public,Telecommunications Services,Telecommunications,$2 to $5 billion (USD),-1,CA,90,109,99.5,27,1,1,0,1,1,0,0,senior
131,132,Senior Data Engineer,90-109,Lendio is looking to fill a position for a Sen...,4.9,Lendio,"Lehi, UT","Lehi, UT",201 to 500 employees,2011,Company - Private,Lending,Finance,$50 to $100 million (USD),-1,UT,90,109,99.5,12,1,0,1,1,1,0,0,senior
140,143,Senior Data Scientist,90-109,Tempo Automation is the world's fastest electr...,3.3,Tempo Automation,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2013,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,$5 to $10 million (USD),-1,CA,90,109,99.5,10,1,0,1,1,1,1,0,senior
151,154,Sr Scientist - Extractables & Leachables,90-109,Sr Scientist - Extractables & Leachables\n\nJo...,3.5,Ritedose,"Columbia, SC","Columbia, SC",201 to 500 employees,1995,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$100 to $500 million (USD),-1,SC,90,109,99.5,28,0,1,0,0,0,0,0,senior
153,156,Sr Data Scientist,90-109,bioMérieux Inc.\n\nSr Data Scientist\n\nSENIOR...,4.2,bioMérieux,"Saint Louis, MO","Marcy-l'Etoile, France",10000+ employees,1963,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$2 to $5 billion (USD),-1,MO,90,109,99.5,60,1,1,0,0,0,0,0,senior
164,167,Senior Data Analyst,101-165,Job Requisition ID #\n20WD38079\nJob Title\nSe...,4.0,Autodesk,"San Francisco, CA","San Rafael, CA",5001 to 10000 employees,1982,Company - Public,Computer Hardware & Software,Information Technology,$2 to $5 billion (USD),-1,CA,101,165,133.0,41,1,0,1,1,0,0,0,senior
165,168,Senior Data Analyst,101-165,"Secure our Nation, Ignite your Future\n\nJob S...",4.2,Autodesk,"San Francisco, CA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,CA,101,165,133.0,55,1,0,1,1,0,1,0,senior
167,170,Sr Data Analyst,101-165,"Position location: Lake Mary, FLorBlue Bell, P...",2.3,United BioSource,"Blue Bell, PA","Blue Bell, PA",1001 to 5000 employees,2003,Other Organization,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$100 to $500 million (USD),"Covance, ICON",PA,101,165,133.0,20,0,1,0,0,0,1,0,senior
171,174,Senior Data Scientist - Algorithms,101-165,Company Description: Quartet is a pioneering h...,3.9,Quartet Health,"New York, NY","New York, NY",201 to 500 employees,2014,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,NY,101,165,133.0,9,1,0,1,0,0,0,0,senior
173,176,Senior Data & Machine Learning Scientist,101-165,Passionate about precision medicine and advanc...,3.3,Tempus Labs,"Chicago, IL","Chicago, IL",501 to 1000 employees,2015,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1,IL,101,165,133.0,8,1,0,0,0,1,0,0,senior
180,183,Sr. Data Scientist II,56-97,Data Scientist\n\nBefore the dawn of everythin...,3.5,Argo Group US,"New York, NY","Hamilton, Bermuda",1001 to 5000 employees,1948,Company - Public,Insurance Carriers,Insurance,$1 to $2 billion (USD),-1,NY,56,97,76.5,75,1,0,1,1,1,0,0,senior
182,185,Senior Data Analyst,56-97,About us\n\n\nLife360 brings families closer w...,3.9,Life360,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2008,Company - Public,Internet,Information Technology,Unknown / Non-Applicable,-1,CA,56,97,76.5,15,1,0,0,0,0,1,0,senior
183,186,Lead Data Scientist,56-97,"Job Description\n\nSince 1851, MassMutuals com...",3.7,MassMutual,"Boston, MA","Springfield, MA",5001 to 10000 employees,1851,Company - Private,Insurance Carriers,Insurance,$10+ billion (USD),-1,MA,56,97,76.5,172,1,0,1,1,1,0,0,senior
187,190,Principal Data Scientist - Machine Learning,56-97,Are you a highly experienced Data Scientist wi...,3.6,Constant Contact,"Waltham, MA","Waltham, MA",Unknown,1995,Subsidiary or Business Segment,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Drip, iContact, Mailchimp",MA,56,97,76.5,28,1,1,1,1,1,0,0,senior
188,191,Principal Machine Learning Scientist,56-97,"Today, nearly every business in the world has ...",4.7,Sage Intacct,"San Francisco, CA","San Jose, CA",501 to 1000 employees,1999,Subsidiary or Business Segment,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1,CA,56,97,76.5,24,1,0,0,0,0,0,0,senior
190,193,Principal Data Scientist,56-97,At AstraZeneca we are constantly pushing the b...,4.0,AstraZeneca,"Gaithersburg, MD","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Roche, GlaxoSmithKline, Novartis",MD,56,97,76.5,110,1,1,0,0,0,0,0,senior
192,195,Senior Data Scientist - R&D Oncology,56-97,"At AstraZeneca,we work together to deliver inn...",4.0,AstraZeneca,"New York, NY","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Roche, GlaxoSmithKline, Novartis",NY,56,97,76.5,110,1,0,0,0,0,0,0,senior
194,197,"Health Plan Data Analyst, Sr",56-97,"Title: Health Plan Data Analyst, Sr\n\nCook Ch...",3.8,Cook Children's Health Care System,"Fort Worth, TX","Fort Worth, TX",5001 to 10000 employees,1918,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),"Children's Health, Texas Health Resources, Bay...",TX,56,97,76.5,105,0,0,0,0,0,0,0,senior
195,198,"Principal Scientist/Associate Director, Qualit...",56-97,Rubius Therapeutics is a clinical-stage biopha...,3.8,Rubius Therapeutics,"Smithfield, RI","Cambridge, MA",201 to 500 employees,2013,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$100 to $500 million (USD),-1,RI,56,97,76.5,10,0,0,0,0,0,0,0,senior
202,205,"Senior Data Scientist – Image Analytics, Novar...",79-106,"15-Apr-2020\n\nJob ID\n279187BR\n{""QuestionNam...",3.9,Novartis,"Cambridge, MA","Basel, Switzerland",10000+ employees,1996,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,MA,79,106,92.5,27,0,0,0,0,0,0,0,senior
205,208,Senior Business Intelligence Analyst,79-106,Position Overview:\n\nThe Senior Business Inte...,3.7,Protolabs,"Maple Plain, MN","Maple Plain, MN",1001 to 5000 employees,1999,Company - Public,Miscellaneous Manufacturing,Manufacturing,$100 to $500 million (USD),-1,MN,79,106,92.5,24,0,0,0,0,0,0,0,senior
209,212,Senior Data Scientist,79-106,Do you have a head for numbers? Like turning r...,3.5,Maxar Technologies,"Herndon, VA","Westminster, CO",5001 to 10000 employees,-1,Company - Public,Aerospace & Defense,Aerospace & Defense,$2 to $5 billion (USD),-1,VA,79,106,92.5,unknown,1,1,0,0,0,0,0,senior
214,217,"Intelligence Data Analyst, Senior",79-106,"Intelligence Data Analyst, Sr\n\nJob Descripti...",4.3,The Buffalo Group,"Fort Belvoir, VA","Reston, VA",501 to 1000 employees,2010,Company - Private,IT Services,Information Technology,$100 to $500 million (USD),"ManTech, Booz Allen Hamilton, Leidos",VA,79,106,92.5,13,1,0,0,0,0,0,0,senior
217,220,"Senior Machine Learning Scientist - Bay Area, CA",79-106,Passionate about precision medicine and advanc...,3.3,Tempus Labs,"Redwood City, CA","Chicago, IL",501 to 1000 employees,2015,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1,CA,79,106,92.5,8,1,0,0,0,1,0,0,senior
232,235,Sr. Data Scientist II,71-123,Data Scientist\n\nBefore the dawn of everythin...,3.5,Argo Group US,"New York, NY","Hamilton, Bermuda",1001 to 5000 employees,1948,Company - Public,Insurance Carriers,Insurance,$1 to $2 billion (USD),-1,NY,71,123,97.0,75,1,0,1,1,1,0,0,senior
236,239,Senior Data Analyst,71-123,About us\n\n\nLife360 brings families closer w...,3.9,Life360,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2008,Company - Public,Internet,Information Technology,Unknown / Non-Applicable,-1,CA,71,123,97.0,15,1,0,0,0,0,1,0,senior
239,242,Senior Research Statistician- Data Scientist,90-124,Acuity is seeking a Senior Research Statistici...,4.8,Acuity Insurance,"Sheboygan, WI","Sheboygan, WI",1001 to 5000 employees,1925,Company - Private,Insurance Carriers,Insurance,$1 to $2 billion (USD),-1,WI,90,124,107.0,98,0,0,0,0,0,0,0,senior
248,251,Lead Data Scientist,90-124,"Job Description\n\nSince 1851, MassMutuals com...",3.7,MassMutual,"Boston, MA","Springfield, MA",5001 to 10000 employees,1851,Company - Private,Insurance Carriers,Insurance,$10+ billion (USD),-1,MA,90,124,107.0,172,1,0,1,1,1,0,0,senior
258,261,Principal Machine Learning Scientist,90-124,"Today, nearly every business in the world has ...",4.7,Sage Intacct,"San Francisco, CA","San Jose, CA",501 to 1000 employees,1999,Subsidiary or Business Segment,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1,CA,90,124,107.0,24,1,0,0,0,0,0,0,senior
259,262,Principal Data Scientist - Machine Learning,90-124,Are you a highly experienced Data Scientist wi...,3.6,Constant Contact,"Waltham, MA","Waltham, MA",Unknown,1995,Subsidiary or Business Segment,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Drip, iContact, Mailchimp",MA,90,124,107.0,28,1,1,1,1,1,0,0,senior
263,266,Director of Data Science,91-150,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,MA,91,150,120.5,42,1,1,0,0,1,0,0,senior
269,272,"Manager / Lead, Data Science & Analytics",91-150,Search by Keyword\nMore Options\n\nSearch by L...,4.1,ABIOMED,"Danvers, MA","Danvers, MA",1001 to 5000 employees,1981,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$100 to $500 million (USD),"Covidien, Boston Scientific",MA,91,150,120.5,42,1,1,0,0,0,1,0,senior
281,284,Senior Analyst/Data Scientist,141-225,At Edmunds were driven to make car buying easi...,3.4,Edmunds.com,"Santa Monica, CA","Santa Monica, CA",501 to 1000 employees,1966,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"TrueCar, Cars.com, Kelley Blue Book",CA,141,225,183.0,57,1,1,0,0,1,1,0,senior
284,287,Senior Data Scientist - R&D Oncology,141-225,"At AstraZeneca,we work together to deliver inn...",4.0,AstraZeneca,"New York, NY","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Roche, GlaxoSmithKline, Novartis",NY,141,225,183.0,110,1,0,0,0,0,0,0,senior
309,312,"Health Plan Data Analyst, Sr",145-225,"Title: Health Plan Data Analyst, Sr\n\nCook Ch...",3.8,Cook Children's Health Care System,"Fort Worth, TX","Fort Worth, TX",5001 to 10000 employees,1918,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),"Children's Health, Texas Health Resources, Bay...",TX,145,225,185.0,105,0,0,0,0,0,0,0,senior
310,313,"Principal Scientist/Associate Director, Qualit...",145-225,Rubius Therapeutics is a clinical-stage biopha...,3.8,Rubius Therapeutics,"Smithfield, RI","Cambridge, MA",201 to 500 employees,2013,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$100 to $500 million (USD),-1,RI,145,225,185.0,10,0,0,0,0,0,0,0,senior
312,315,Senior Data Scientist,145-225,About Us\n\nOn the off chance you've thought a...,3.8,Metromile,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2011,Company - Private,Insurance Carriers,Insurance,Unknown / Non-Applicable,-1,CA,145,225,185.0,12,1,0,0,1,1,0,0,senior
329,332,Principal Data & Analytics Platform Engineer,79-147,Additional Locations:\nJob Description\nRespon...,3.7,Blue Cross and Blue Shield of North Carolina,"Durham, NC","Durham, NC",1001 to 5000 employees,1933,Company - Private,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1,NC,79,147,113.0,90,1,1,0,1,1,0,0,senior
332,335,"Senior Data Scientist – Image Analytics, Novar...",79-147,"15-Apr-2020\n\nJob ID\n279187BR\n{""QuestionNam...",3.9,Novartis,"Cambridge, MA","Basel, Switzerland",10000+ employees,1996,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,MA,79,147,113.0,27,0,0,0,0,0,0,0,senior
340,343,"VP, Data Science",79-147,"We are looking for a VP, Data Science to lead ...",3.9,7Park Data,"New York, NY","New York, NY",51 to 200 employees,2012,Company - Private,Research & Development,Business Services,Unknown / Non-Applicable,-1,NY,79,147,113.0,11,1,1,0,1,0,0,0,senior
343,346,Senior Business Intelligence Analyst,122-146,Position Overview:\n\nThe Senior Business Inte...,3.7,Protolabs,"Maple Plain, MN","Maple Plain, MN",1001 to 5000 employees,1999,Company - Public,Miscellaneous Manufacturing,Manufacturing,$100 to $500 million (USD),-1,MN,122,146,134.0,24,0,0,0,0,0,0,0,senior
356,364,Senior Data Scientist,122-146,Do you have a head for numbers? Like turning r...,3.5,Maxar Technologies,"Herndon, VA","Westminster, CO",5001 to 10000 employees,-1,Company - Public,Aerospace & Defense,Aerospace & Defense,$2 to $5 billion (USD),-1,VA,122,146,134.0,unknown,1,1,0,0,0,0,0,senior
370,378,Sr. Data Scientist,112-116,The position\n\nCome join one of the fastest-g...,3.5,Evolve Vacation Rental,"Denver, CO","Denver, CO",201 to 500 employees,2011,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,-1,CO,112,116,114.0,12,1,0,0,0,0,0,0,senior
377,385,Senior Data Analyst - Finance & Platform Analy...,112-116,"About Us\n\n\nLaunched in 2011, Twitch is a gl...",3.6,Twitch,"San Francisco, CA","San Francisco, CA",1001 to 5000 employees,2011,Subsidiary or Business Segment,Internet,Information Technology,Unknown / Non-Applicable,-1,CA,112,116,114.0,12,1,0,0,0,0,1,0,senior
378,386,Senior Data Scientist,110-163,Klaviyo is looking for Senior Data Scientists ...,4.8,Klaviyo,"Boston, MA","Boston, MA",201 to 500 employees,2012,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1,MA,110,163,136.5,11,0,0,0,0,0,0,0,senior
382,391,"Senior Machine Learning Scientist - Bay Area, CA",110-163,Passionate about precision medicine and advanc...,3.3,Tempus Labs,"Redwood City, CA","Chicago, IL",501 to 1000 employees,2015,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1,CA,110,163,136.5,8,1,0,0,0,1,0,0,senior
384,393,Senior Clinical Data Scientist Programmer,110-163,Description and Requirements\n\nMedAvante-Prop...,3.6,WCG (WIRB-Copernicus Group),"Hamilton, NJ","Princeton, NJ",1001 to 5000 employees,-1,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$100 to $500 million (USD),-1,NJ,110,163,136.5,unknown,0,1,0,0,0,0,0,senior
392,401,Senior Data Analyst,110-163,Join our team dedicated to developing and exec...,4.5,Novetta,"Herndon, VA","Mc Lean, VA",501 to 1000 employees,2012,Company - Private,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"Leidos, CACI International, Booz Allen Hamilton",VA,110,163,136.5,11,1,1,0,0,0,0,0,senior

In [351]:
#drop index column
df.drop('index', axis = 1, inplace = True )

In [352]:
df.head()

,Job Title,Salary Estimate(K$),Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,State,Min_Salary,Max_Salary,AVG_Salary,Company_Age,python,excel,hadoop,spark,aws,tableau,big_data,Seniority
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",NY,137,171,154.0,30,0,0,0,0,1,0,0,senior
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,VA,137,171,154.0,55,0,0,1,0,0,0,0,all level
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,MA,137,171,154.0,42,1,1,0,0,1,0,0,all level
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",MA,137,171,154.0,23,1,1,0,0,1,0,0,all level
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",NY,137,171,154.0,25,1,1,0,0,0,0,0,all level